/**
 * NanoBanana Pro Service
 * Handles scene composition using Gemini 3 Pro Image Preview
 */

import { GoogleGenAI } from '@google/genai';
import { loadImage, type ImageData } from '../utils/image.js';
import { buildScenePrompt, type ScenePromptOptions } from '../utils/prompts.js';
import type { DuoCastConfig, AspectRatio, ImageSize } from '../config.js';

export interface CompositeSceneResult {
    imageData: string;      // Base64 encoded image
    mimeType: string;
    prompt: string;         // The prompt used for generation
}

export interface NanoBananaOptions {
    aspectRatio?: AspectRatio;
    imageSize?: ImageSize;
    customPrompt?: string;
}

export class NanoBananaService {
    private ai: GoogleGenAI;
    private config: DuoCastConfig;

    constructor(config: DuoCastConfig) {
        this.config = config;
        this.ai = new GoogleGenAI({ apiKey: config.apiKey });
    }

    /**
     * Generate a composite scene with both portraits
     * Uses up to 5 human reference images for character consistency
     */
    async generateCompositeScene(
        portraitAPath: string,
        portraitBPath: string,
        scenario: string,
        options: NanoBananaOptions = {}
    ): Promise<CompositeSceneResult> {
        console.log('🎨 Loading portrait images...');

        // Load both portrait images
        const portraitA = loadImage(portraitAPath);
        const portraitB = loadImage(portraitBPath);

        // Build the scene prompt
        const promptOptions: ScenePromptOptions = {
            scenario,
            setting: 'the specified scenario setting',
        };

        const prompt = options.customPrompt || buildScenePrompt(promptOptions);

        console.log('🖼️  Generating composite scene with NanoBanana Pro...');
        console.log(`   Model: ${this.config.nanoBanana.model}`);
        console.log(`   Aspect Ratio: ${options.aspectRatio || this.config.nanoBanana.aspectRatio}`);
        console.log(`   Resolution: ${options.imageSize || this.config.nanoBanana.imageSize}`);

        // Build the content parts with both images
        const contents = [
            { text: prompt },
            {
                inlineData: {
                    mimeType: portraitA.mimeType,
                    data: portraitA.data,
                },
            },
            {
                inlineData: {
                    mimeType: portraitB.mimeType,
                    data: portraitB.data,
                },
            },
        ];

        try {
            // Call NanoBanana Pro (Gemini 3 Pro Image Preview)
            const response = await this.ai.models.generateContent({
                model: this.config.nanoBanana.model,
                contents: contents,
                config: {
                    responseModalities: ['TEXT', 'IMAGE'],
                    // @ts-ignore - imageConfig is available but types may be outdated
                    imageConfig: {
                        aspectRatio: options.aspectRatio || this.config.nanoBanana.aspectRatio,
                        imageSize: options.imageSize || this.config.nanoBanana.imageSize,
                    },
                },
            });

            // Extract the generated image from response
            const candidate = response.candidates?.[0];
            if (!candidate?.content?.parts) {
                throw new Error('No content received from NanoBanana Pro');
            }

            let imageData: string | null = null;
            let mimeType = 'image/png';

            for (const part of candidate.content.parts) {
                if (part.text) {
                    console.log('   Model response:', part.text.substring(0, 100) + '...');
                } else if (part.inlineData) {
                    imageData = part.inlineData.data || '';
                    mimeType = part.inlineData.mimeType || 'image/png';
                }
            }

            if (!imageData) {
                throw new Error('No image generated by NanoBanana Pro');
            }

            console.log('✅ Composite scene generated successfully!');

            return {
                imageData,
                mimeType,
                prompt,
            };
        } catch (error) {
            console.error('❌ Failed to generate composite scene:', error);
            throw error;
        }
    }
}
